### ISSUE TITLE
Various Suggestions

### ISSUE THREAD

**Issue by Andre601** [DecentSoftware-eu/DecentHolograms#1]
This issue is for me to make various suggestions which could help improving the plugin and adding QoL changes to it that benefit the end-users.

### 1. Relative coordinates support for move
When moving the Hologram would it be cool to have a way of using relative coordinates to move the hologram relative to its current position.
This is especially useful, if you added new lines and need to move the hologram up a bit.

Example:
```
/dh holo move example ~ ~2 ~
```
This would move the hologram 2 block up from its current position.

### 2. JSON text for quick actions (add line, set line, etc.)
This is imo one of the best features in HolographicDisplays and I would love if DecentHolograms could also include it.
The idea would be that DH would display a line of text with quick actions such as adding a new line to the hologram you just interacted with.

For example would running `/dh holo create example` print the line `[Add line] [Set line] [Insert Line] [Delete Hologram]` where each text has one of the corresponding commands attached.
So would clicking `[Add Line]` insert the command `/dh l add example ` into the player's chatbar for them to finally add the text to it.

This could speed up the process of editing holograms.

And while we're at commands...

### 3. Better command syntax
I personally don't get the appeal of having creating and deleting holograms and editing lines in separate sub-commands...

In general is the whole command syntax a bit confusing, but this is mostly because I'm used to HolographicDisplay's command syntax at this point.

I still think tho that a switch from like `/dh holo create example` to just `/dh create example` would be good since I don't see any particular reason why it should have this specific `holo` distinction.

Personally can I understand if this won't be changed as it could cause confusion amongst people that are already used to the current syntax, but I hope you consider to improve it in some way.

**Comment by D0bbyVoe** [comment]
Thank you very much for your suggestions, I sure will consider adding these features. I'm currently working on a big update that's dropping very soon so I will implement some of these suggestions in that update.

### 1. Relative coordinates support for move
This is overall a good idea and I will implement that in the upcoming update.

### 2. JSON text for quick actions (add line, set line, etc.)
I actually already thought about that but I will add that later.

### 3. Better command syntax
Now, let me explain the command syntax. The reason for various subcommands is that there is just too many, even similar commands for holograms and lines. I haven't found any better solution for differentiating them yet. But I will add some shortcuts for heavily used commands like `/dh create example` instead of `/dh holo create example`.

**Comment by Andre601** [comment]
With version 2 and the animation option did I had another idea: Pre-made text-effects/animations.

The idea would be to offer something like `<RAINBOW1>` or the `&u` colour but differently.
For the rainbow one could the text just cycle through a smooth rainbow gradient compared to `&u`'s more simple system.
Or perhaps even have a gradient going through the text that is animated? Like what you can see in scoreboard plugins being showcased...

Of course this would add more complexity to how the plugin should handle the text and all...

**Comment by Andre601** [comment]
I close this as most if not all suggestions have been implemented. If some aren't added yet, let me know and I re-open.
