### ISSUE TITLE
Holograms with pages are slow to load and causes huge tps drop

### ISSUE THREAD

**Issue by NLogDEV** [DecentSoftware-eu/DecentHolograms#147]
### Just making sure

- [x] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Create a holograms with pages
3. Switch between pages a few times
4. This happens... (Look at the video)
[bugreport.webm](https://github.com/DecentSoftware-eu/DecentHolograms/assets/85012778/99a0435d-e1e4-46ca-b369-cab9ed5106e1)

### Server Version

PandaSpigot version git-PandaSpigot-111 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Client Version

Lunar Client (1.8.9)

### Plugin Version

v2.8.3

### Log

https://pastebin.com/U6n0nSVt

**Comment by Andre601** [comment]
Mind uploading the vid to t or similar? It stops playing for me after a few seconds.

Also, if the issue is old pages not getting replaced, then that is normal, as some packets send by the server can be ignored by the client at random.

Also, for proper reproduction steps please...
- Use Paper and not a fork
- Use vanilla client and not a modded one

The client one is important because modded clients, especially Lunar, can change stuff DH uses.

**Comment by NLogDEV** [comment]
I've tried Paper and also vanilla mc 1.8 client as well, but the issue still exist by spamming actions on the hologram.

**Comment by qlnn** [comment]
skill issues

**Comment by d0by1** [comment]
This just seems to be problem with the placeholders you are using. The implementation of that placeholder extesion is probably very poorly optimized and the issue should be reported to the author of that extension.
