### ISSUE TITLE
Loading Denizen placeholder cause async issue

### ISSUE THREAD

**Issue by Josh65-2201** [DecentSoftware-eu/DecentHolograms#159]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install Denizen https://ci.citizensnpcs.co/job/Denizen/
2. Add `%denizen_<player.flag[leaderboardOne].if_null[0]>%` to hologram line
3. See PlaceholderAPI show async access error

### Server Version

Paper 1.20.1 build 196

### Client Version

1.20.1

### Plugin Version

2.8.4

### Log

https://pastebin.com/F8xk6sjb

**Comment by Andre601** [comment]
I feel like this is an issue with Denizen itself and not DH.

All DH does is pass the lines to PlaceholderAPI to parse any placeholders in it. It does it on an async threat because that's just better for performance. Running it on the main thread - which would be the only alternative - would be awful design as it could tank performance hard if there are a lot of players and/or placeholders to handle here...

So having Denizen complain it's not sync and/or on main thread is honestly just a stupid design and shows bad optimization on their end.

Tho, take this with a grain of salt, as I'm no expert in this entire sync vs async thing. Tho I so far have never seen any complains about DH's async placeholder parsing causing issues.

**Comment by d0by1** [comment]
Hello, Andre is absolutely correct. I don't see a reason why the placeholders should only be updated synchronously. Parsing placeholders on the main thread would just cause performance issues. With that said, I'm not going to implement this change just because one plugin complains. You will need to find another solution (or report this to Denizen's developers).

**Comment by analnyroztahovac** [comment]
> I don't see a reason why the placeholders should only be updated synchronously. 
Valid denizen placeholder may contain tags that go through some Bukkit API methods (nothing in Bukkit is async safe unless documentet as safe) which is exactly why they should be parsed sync

**Comment by mcmonkey4eva** [comment]
See for reference _the giant screenshot_ for explanation for why Denizen gives a warning on async placeholders
it can technically be disabled but it is entirely a fault with DecentHolograms using unsafe async, Denizen isn't causing an error rather it's trying to warn you that something's gone wrong and save you from it. Use async here regardless under your own willful self-destruction.

![2fdd06](https://github.com/DecentSoftware-eu/DecentHolograms/assets/4000772/b391bbe1-0de1-496b-9723-5662ce0703db)
