### ISSUE TITLE
NoSuchMethodError when getting string from PLAYER_HEAD with skin through HologramItem.fromItemStack()

### ISSUE THREAD

**Issue by i998979** [DecentSoftware-eu/DecentHolograms#166]
### Just making sure

- [x] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Have this piece of code
`ItemStack item = player.getInventory().getItemInMainHand();
Bukkit.broadcastMessage(HologramItem.fromItemStack(item).toString());`
3. Run the code
4. `java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'`

### Server Version

git-Paper-290 (MC: 1.20.2)

### Client Version

Vanilla 1.20.2

### Plugin Version

2.8.5

### Log

https://pastebin.com/npqaYa85

**Comment by MineFact** [comment]
Ok so first of all, no https://github.com/DecentSoftware-eu/DecentHolograms/pull/169 will not fix this issue.

I digged deeper into the code and found out what causes the issue. 

This is the method we are talking about:
https://github.com/DecentSoftware-eu/DecentHolograms/blob/673e45c724910021d47f23257845c659cb60db17/src/main/java/eu/decentsoftware/holograms/api/utils/items/SkullUtils.java#L66-L70

The problem is that DecentHolograms uses the Spigot 1.13 library right now.
Spigot 1.13 uses an old Mojang Authlib version that is outdated. 
In the latest Spigot 1.20.2 dependency the new version of Mojand Authlib is used though with version 5.0.47
In this version, the properties class changed and now does not have getters like `getValue()` anymore.
Instead the value is read with `value()`. 

So to fix this you can import the latest Mojang Authlib libary and change the property getter from `getValue()` to `value()`.
This will break any usage in older Minecraft Versions though. Unfortunately I'm not that experienced with multi version support, otherwise I would have created a pull request for you.

So someone else needs to fix that. 
For anyone who wants this to be fixed for his latest Minecraft version in the meanwhile, import this in the build.gradle and change the methods as described above.
```gradle
compileOnly 'com.mojang:authlib:5.0.47'
```

**Comment by Andre601** [comment]
Reflection could be used here probably to find the right method...
