### ISSUE TITLE
Legacy Support

### ISSUE THREAD

**Issue by Zilacon** [DecentSoftware-eu/DecentHolograms#178]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

Plugin does not support legacy versions.

### Feature

Added legacy support down to 1.5 to replace the currently used HolographicDisplays.
I run dozens of servers, 15 of them 1.7 and below, and need a displays plugin that not only works on those versions but can be used on our multi-version hub to be viewable from clients on those versions.

### Alternatives

None.
Id appreciate any help to do this, as i no longer have the active developers to make custom plugins like this as 2 of my devs died in 2020 and made the 3rd also leave.
Also merry christmas!

**Comment by d0by1** [comment]
This is probably not going to happen. To make it work with versions 1.7 and below, I'd need to make some big changes to the entire plugin. I had to jump through hoops just to get it working with 1.8. First off, the plugin relies on the Spigot API, which only works with 1.8 and newer. Plus, there are some important features in 1.8 that just aren't in 1.7. It's not impossible, but it would take a ton of work and a lot of my time. And since there aren't many people still using those old versions, it's just not worth it.

I'm sorry, but you'll likely have to stick with HD on these old servers. I believe even the latest HD versions do not support 1.7 and below. The only reason HD ever supported these versions is because the plugin was first made when those versions were the latest.

**Comment by Zilacon** [comment]
Spigot API was made on 1.4.7, and all of my servers on 1.5+ use spigot. But ok.

**Comment by Andre601** [comment]
Supporting such old versions makes absolutely no sense.
There is no logical reason why versions before 1.8 should still be used. They are old, buggy, lack a lot of features and most importantly do not have armor stands to use.

**Comment by Zilacon** [comment]
Mods: Exist.
Andrew601: Is this a outdated version?

**Comment by Andre601** [comment]
Most mods people and server use also exist on much newer versions.

Also, the use of hybrid servers that merge plugin and mod APIs is NOT recommended as they break countless things in the process, requiring a lot of work from plugin devs to support them.

Also, the fact the Spigot API existed back then does not mean it offers everything DH needs to work.

**Comment by Zilacon** [comment]
And yet there's a lot of mods that are discontinued by the devs, and never get updated.
Which means players have to play on a outdated modpack to continue playing with that mod.
There is also the case of players wanting to play on modpacks they did years ago for nostalgia's sake.
Just because its old doesn't mean it doesn't hold meaning to others, this is a common bias in the mc dev community.

Hybrid servers were invented by the forge dev team, which then invented sponge which every dev nowadays basically admires.
The same devs who made plugins like essentials, worldedit, griefprevention, etc are all on the sponge dev team.
Which adds plugins to forge. Which is the same purpose of a hybrid server. Which is what the original forge+spigot servers did and still do. Just in a different way.

There is nothing a hybrid server can do that will impact the use of a plugin like holographic displays. Its been used on 40 different modpacks by myself, and hundreds of others by other people with no issues. Yes hybrid servers create SOME issues with forge, but the amount of them that ive experienced is very small. Using sponge however seems to literally launch a tactical nuke at every mod it touches.

**Comment by Andre601** [comment]
You simply don't get it.

No matter how much nostalgia you put into an old version, it is still an old version that no dev worth his salt is actively supporting these days.
Also, the fact that devs of popular plugins are also part of the Sponge team has 0 meaning here. Devs can work on countless things... Like the Dev of ViaVersion is also an active dev of Paper itself, but this has 0 meaning on either side here.

And regarding Sponge: This is a server software that has been build with the Modding and plugin API in mind. The API they provide is nowhere near the same as what Spigot has here, and is much more adabted to the behaviours of the modding API, which can change and alter the MC server's internal code.

And that is already the issue with hybrid servers that aren't Sponge: They hack together two incompatible APIs and try to fix the mess they create later. The Spigot API is rigit and not build for modding, which itself allows modifications of the server code itself by injecting, removing or modifying parts of it at runtime.

And I'm 120% confident that DH would never work on a Hybrid Server. It doesn't only rely on the Spigot API but also accesses things through reflection. And a Hybrid Server may change parts DH accesses causing unwanted side effects and issues in the process.

Do everyone a favour and just drop this topic already. It is clear enough that d0by won't add support for ancient versions just because a single person asks for it. He already stated that 1.8 support is already a huge pain, so this here wouldn't be any easier and require even more modifications on the plugin end.
Not to mention the lack of armor stands and iirc the feature to make entities marker entities, so they won't be ticked by the server (Which improves performance).
