### ISSUE TITLE
DHAPI creates empty files

### ISSUE THREAD

**Issue by FortuneMidnight** [DecentSoftware-eu/DecentHolograms#197]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. create new holograms via api
3. after creation, set savetoFile false
4. in the decentholograms plugin folder, in holograms folder are the empty hologram files
![idea64_GqHGuS7LqB](https://github.com/DecentSoftware-eu/DecentHolograms/assets/74560632/36848fe4-8767-489d-8b69-30367831e418)

Although saveToFile is set to false, empty files are created in the Holograms folder of DecentHolograms

### Server Version

1.20.4

### Client Version

1.20.4

### Plugin Version

v2.8.6

### Log

not needed

**Comment by Andre601** [comment]
You use the API wrong.

To create a new Hologram, use `DHAPI.createHologram(String, Location)`

The way you do it is not recommended nor a proper way of doing it.

**Comment by Andre601** [comment]
And to clarify further:
In the `Hologram(String, Location, boolean)` constructor does a true boolean value cause `new FileConfig(...)` to be called, which creates a new file, since it assumes the Hologram to be saved later on.

And calling `Hologram(String, Location)` is calling the other constructor with the boolean argument set to true.
