### ISSUE TITLE
Updating holograms (flickering)

### ISSUE THREAD

**Issue by JanReich** [DecentSoftware-eu/DecentHolograms#207]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Create Holograms with API
3. Create Holograms via ingame command
4. Donwload and install typewriter plugin
5. Create a cinematic 
6. Play and view cinematic
7. The command generated hologram are flickering

https://github.com/DecentSoftware-eu/DecentHolograms/assets/31835586/94142083-d5aa-4934-ac68-ed25424d74e8

### Solution

Maybe there is a difference in the rendering of the command generated holograms and the api generated holograms and this issue could be fixed. The quick fix would be to render all holograms via api, but it would be realdy nice if this bug could be fixed

### Server Version

1.20.4 Paper

### Client Version

1.20.4

### Plugin Version

2.8.6

### Log

.

**Comment by Andre601** [comment]
I think this is more likely an issue with the cinematic plugin, causing packets to be broken here...

**Comment by d0by1** [comment]
DH is in fact the culprit here. Whenever a player teleports, all holograms temporarily disappear and then reappear. This fix was introduced to address visibility problems previously encountered. It's not necessary for all Minecraft versions though and I'm planning to improve it. However, a lot of testing will have to be done and haven't found time for it yet. But I'm aware of this issue and will fix it eventually.

**Comment by d0by1** [comment]
Hello, this issue has been resolved in DH v2.8.9. I added a new option in `config.yml` called `update-visibility-on-teleport`, which is set to `false` by default.
