### ISSUE TITLE
Add entity type (besides mobs) "PLAYER" too, with all its attributes

### ISSUE THREAD

**Issue by TheJoshue** [DecentSoftware-eu/DecentHolograms#212]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

i know there is Citizens plugin but it stopped supporting a lot of versions and focuses on newer only...

### Feature

so we currently can use
```
#ENTITY: <entity>
```
in a way for example:
```
#ENTITY: PIG
```

but what about:
```
#ENTITY: PLAYER
```
and even better (i am not sure how would this be written NBT-wise, so take my suggestion just as a rudimentary example please):
```
#ENTITY: PLAYER {Username:<player_username_here>}'
```
so for example:
```
#ENTITY: PLAYER {Username:Notch}'
```

you get the point

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
From what I know are there particular reasons why you can't have player skins displayed...

But it doesn't matter anyways, because DecentHolograms is a holograms plugin. Having Entities displayed is just a small, but not primary feature of it.
If you want to use player skins, use an NPC plugin like Citizens. Yes, they only support latest main releases (And 1.8.8 for whatever reason), but you can just use an older version that still supports the release you want? Or even better: Just update your server.

**Comment by d0by1** [comment]
Hello, this will not be added. Andre explained the reasons well. Sorry.
