### ISSUE TITLE
Ability to use animations inside placeholders

### ISSUE THREAD

**Issue by z2vvqx** [DecentSoftware-eu/DecentHolograms#239]
### Just making sure

- [X] I have read the wiki and made sure, this feature is not yet in the plugin.
- [X] I believe, that this feature is possible to implement.
- [X] I made sure, that this feature has not been requested yet.

### Problem

I am unable to achieve 'the ability of parsing the animations that are sent with my placeholder, I want to display an animation with the placeholder I'm sending'
I think it would be useful for 'displaying animations inside placeholders, such as if the placeholder doesn't exist for a certain name. I can display an animated "Unavailable..." with the dots animating and etc.'

### Feature

I would like to see 'ability to parse animations that are sent within placeholders'

### Alternatives

It would also be possible by doing '...'

**Comment by Andre601** [comment]
That is pretty much impossible to do here.
DH does nothing more than sending the line to PlaceholderAPI to parse and display whatever it returns.

Anything related to placeholders has to be done by the Placeholder expansion and not DH.

**Comment by d0by1** [comment]
So you want to use animations in values returned by placeholders right? Like a placeholder returning `<#ANIM:...>...</#ANIM>`?

Animations like that will currently not work. The problem is this line: https://github.com/DecentSoftware-eu/DecentHolograms/blob/a1374985faa80165aecccb4ad230231cfa8950e6/src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java#L322

Question is, if we want to allow this. It doesn't seem to bring much value for the performace impact it would have. We would have to check for the animations on every content update and there is a good reason we don't do that. Maybe a config option could be added, similar to the one allowing placeholders inside animations.
