### ISSUE TITLE
DH with Conflit with SpoofEngine plugin

### ISSUE THREAD

**Issue by AffonsoGames** [DecentSoftware-eu/DecentHolograms#255]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

1. Install DecentHolograms...
2. Install SpoofEngine plugin
3. Connect player in the server
4. Console send "reload in the decentholograms"

### Solution

I think what causes the problem is the incompatibility of both because it uses fake player and decent conflicts with protocollib and spoofengine, this happens even with a real player if you have decentholograms & spoofengine

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.8.11

### Log

https://hastebin.com/share/limexinamu.markdown

**Comment by Andre601** [comment]
The paste you shared does say absolutely nothing.

**Comment by AffonsoGames** [comment]
Exactly, it doesn't make any mistakes!

The error that occurs is that every time a player connects to the server, decentlograma restarts

**Comment by Andre601** [comment]
That can't be a DH issue here.
DH doesn't depend on any other plugin, except PlaceholderAPI which is optional and only for placeholder support.

So whatever makes DH reload for player joins is not caused by DH itself but most likely by another plugin (probs that SpoofEnginge plugin) forcing a reload.

Also, Spoofing plugins should imo be avoided. They are usually not good and only waste time and resources for barely any gain in the end.

**Comment by AffonsoGames** [comment]
Thank you for your support and guidance, can you finish please?
