### ISSUE TITLE
Plugin performance cpu usage

### ISSUE THREAD

**Issue by PedroMPagani** [DecentSoftware-eu/DecentHolograms#74]
Why would you start a fixed single thread pool with a thread with MAX_Priority? 

Spark report: https://spark.lucko.me/ZCiHAUO61m

**Comment by Andre601** [comment]
Can you follow the issue templates please?

**Comment by PedroMPagani** [comment]
It isn't a bug, I'm trying to find a dev report somewhere and I can't find a template, sorry

**Comment by PedroMPagani** [comment]
Here's a spark report with DecentHolograms performing in 1 instance:
https://spark.lucko.me/ZCiHAUO61m

**Comment by PedroMPagani** [comment]
A good solution to reduce the cpu usage of the colors is to maybe cache the results, entry?

**Comment by d0by1** [comment]
Hello, you can PR your changes and I will check it out. I think you are just trading memory usage for cpu usage. CPU usage will improve but at the same time, more memory will be used. It could help though.

**Comment by PedroMPagani** [comment]
Yes D0by, that's caching :). I cannot PR it, I am just making a suggestion, my PR will break some functionality for some servers since it includes not having placeholders-related-to players specifically in them, my patches don't consider that, since its done specifically for a network I work for.

But if you want some logic its simple:

1) Not set the thread to high priority, because it's basically not.

2) Cache texts that are equal, make sure the hologram lines don't contain placeholders related to players, this should be made as a config, because you simply can't identify which are related to player and which are not, so leaving it to the user would be good.

3) a high cpu usage comes form the colorize, but also, some good cpu usage comes from the AnimationManager pattern usage, in which I was not able to cache for some reason.

4) This would be 100% more of a common improvement for the plugin than actually something big necessary, the only reason why I had to do this caching is because the cpu usage was quite a lot considering my infrastructure right now, which consists in 5 gamemode instances and each instance is connected to each other including the entities being shown but fakely, so the extra cpu usage was not really good for that scale already O(n) on every action.

Its good to mention that, because I just opened it in case you're interested in improving it for the future, thanks!

**Comment by d0by1** [comment]
Of course, I know what caching is but in this case it's quite difficult to implement. As you said, some placeholders are per-player, meaning we would either have to exclude them or cache the results per-player as well. Considering it's probably not even possible to tell which placeholders are per-player, the second option is the only possible option. Now, caching stuff per-player at this scale (having unknown amount of placeholders in unknown amount of holograms, pages and lines with each placeholder having to be cached per-player), that's a lot of memory. 

**To explain a little further (answering your points):**

1. I will set the priority to normal (5). I have no idea why it was at max.
2. This would just make it much more difficult to setup the plugin which we definitely don't want.
3. Caching colors is just not possible because of gradients, placeholders, etc. The string might change in length which would break stuff. The pattern usage in animations is, I think, only avoidable by not using animations. 
4. The problem with the whole idea is that this plugin is used on literally thousands of servers. Some people want placeholders to work inside animations and some people want more performance. It's just really difficult to fit everyones need. What's more is that there have been people complaining about how much memory this plugin uses. So, even if I implemented something like this, someone else would complain.

**What could we do about it?:**

1. I know the current code is not optimal. It's slow in some places and poorly structured. (That's why I'm already working on rewrite.) We could go through the code and optimize it. Some things could be done better so we could definitely improve that.
2. We could at least cache results of some cpu-intensive checks. For example, we don't have to create a matcher and look for animations in lines, that we know don't contain them. (Same for placeholders.) (This is actually something that could help a lot and we will definitely do it asap.)
3. We will also just study the code a little further and possible implement more optimizations on the way. To be honest, I don't even know how some things are implemented currently.

**Comment by PedroMPagani** [comment]
I understand all your points, and people will always complain no matter what haha.
One of the things I know is that DecentHolograms have a reputation of being the best 1.19 hologram plugin out there, because it doesn't cause any lag in the main thread.

1) You know what else you could do instead? A configuration making the hologram updatable or not, if the hologram is supposed to update it basically has the .tick(), otherwise, if the hologram is not, it basically replaces the placeholders but not per player, that would reduce the o(n) in some of the holograms, since if the hologram is not supposed to update, it wont be per player, you know what I mean?

2) To not affect how configuration works or anything like that, make it default supposed to update, and if not, doesn't loop through all players and keep calling ```getText(..)```.

**Comment by d0by1** [comment]
You can disable updating for a hologram (or a hologram line) using flags. You can find how to do that on the wiki. It doesn't update at all with this setting tho. Animations and placeholders can also be disabled like this, reducing the matcher usage. This might actually be what you are looking for as these flags can be used to disable stuff you don't need.

**Comment by d0by1** [comment]
Hello, just to let you know. We just released an update, in which we hopefully optimized the plugin quite a lot. It would be amazing if you let me know whether or not things got better.

**Comment by PedroMPagani** [comment]
I'll run some bots and will be back with a report later!

**Comment by PedroMPagani** [comment]
Take a look in here:

https://github.com/DecentSoftware-eu/DecentHolograms/blob/main/src/main/java/eu/decentsoftware/holograms/api/holograms/HologramLine.java


The colors matching etc are the thing that most uses the cpu, you should be caching them instead, the problem is, you're calling the .colorize at the end, which causes it to be caching the results containing the players placeholders applied already, that's why it will use a lot of memory, that's not what you should be doing. ( =so the cache endedup going in the wrong way)

1) Cache the raw line, example: "%eco_user_balance% colors somemoretexthere" as key,
cache the value, being the raw line, but colorized.

2) This way you'll have the string colorized, and will use much less cpu time, and you of course, apply the placeholders on that colorized string, this way you'll have the colorized along with the placeholders, which usually are just cache returning and won't consume any cpu, if they do, its other devs fault not yours anyways.

**Comment by Andre601** [comment]
Isn't the main issue with that the fact that placeholders for the most part are non-static?

Sure, there are placeholders like `%player_name%` and similar that return a constant value (Sometimes based on the player), but not every placeholder is like that. Like `%server_online%` may return 10 at one point and 9 later since a player left the server, so caching the result based on the raw value would be counter-productive towards having the placeholders up-to-date in the String itself.

Also, caching stuff, while less heavy on the CPU, can have a negative impact on memory. After all does the data need to be stored somewhere and as long as it isn't a file or database is that the Memory.
So in the end would you trade some CPU reduction for heavier Memory consumption which at least for me seems like a much worse outcome here.

From my testings aren't there that many issues in terms of performance, at least when viewing from a player-perspective which should be your primary goal here anyways, so I doubt updating the colour handling would be that good.

Also, considering DH3 will most likely use Adventure and the MiniMessage format, I can assume that this would already come with some improvements as Adventure is already quite well made.

**Comment by PedroMPagani** [comment]
1) Counter productive why? Since parsing the colors mainly only once for the raw line would result in not having to parse every single time for each payer, I clearly don't see the reason of NOT to do it, i literally said to cache the raw line with the colors parsed, that means not parsing the player placeholders, and you would get the cached line with the colors parsed, and then you would apply the placeholders in it, that's clearly improvement on cpu usage.

2) How can it be heavier memory consumption if you're caching the line rawly ONCE, its not per player, it doesnt matter if you have 2000 players, the raw line doesn't change!

**Comment by Andre601** [comment]
> 1. i literally said to cache the raw line with the colors parsed, that means not parsing the player placeholders, and you would get the cached line with the colors parsed, and then you would apply the placeholders in it, that's clearly improvement on cpu usage.

Well, let me drop a bomb here now: What if a placeholder returns a colour? Like what if someone f.e. displays the Prefix of a Group and said prefix has a colour code? How should DH deal with that if placeholder parsing comes AFTER colour parsing? It would essentially need to do a second go here which destroys any possible efficiency in the end.

> 2\. How can it be heavier memory consumption if you're caching the line rawly ONCE, its not per player, it doesnt matter if you have 2000 players, the raw line doesn't change!

There is still the issue of having to check if the line changed to update the cache which in the end will create new entries in the memory until the old one is taken by the GC, which may not work efficiently if not configured right (And most people aren't aware about those startup-flags to improve things like GC).

> 3\. Please, if you haven't seen improvements, run a infra of 3 instances and add 150 bots to each one, with, and without the decent holograms, and you'll clearly see a decrease of the cpu load.

I still view this from a player-perspective. More CPU is taken up? Okay, fine. But does it affect the player on the server? Do they notice lag, delays or similar in the end?
I'm all in for improving performance as a whole, but not at the cost of implementing a system that would have obvious flaws as I pointed out already.
