### ISSUE TITLE
Holograms disappear in a certain case

### ISSUE THREAD

**Issue by Fredh1000** [DecentSoftware-eu/DecentHolograms#86]
### Just making sure

- [X] I made sure, this bug is not already known or reported.
- [X] I believe, that this bug is fixable.

### Reproduction

Install DecentHolograms 2.7.5 on 1.8.8 server (I tested this on WindSpigot, Paper, NachoSpigot, GuardSpigot and Titanium).
Start server.
Create holograms (In my holograms I have 128 of hologram's display range and 64 of hologram's update range).
This happens:
  - Link of the video showing this problem: https://www.youtube.com/watch?v=SUpUEHqhbsI

### Server Version

1.8.8

### Client Version

1.8.8

### Plugin Version

2.7.5

### Log

It shows no errors during the process, so they are not necessary.

**Comment by d0by1** [comment]
Hello, 

this is actually something I cannot fix, at least not for 1.8. The issue is, that 1.8 client does a terrible job at managing entities. Basically, once you fly too far away from an entity, it will disappear for you no matter what even though the server thinks you still see it. That's why DH does automatically hides and shows entities when needed, that's why the display-range is even an option. 

Now, to fix this, lower your display-range to about 48 blocks. This is the only way to avoid this as on these numbers it is tested, that everything does work fine and entities do show up. You wouldn't even be able to see the holograms from farther away anyway.
